# GitHub funding options
# Uncomment and add your details

# github: [yourusername]
# patreon: yourusername
# open_collective: projectname
# ko_fi: yourusername
# custom: ["https://paypal.me/yourusername", "https://buymeacoffee.com/yourusername"]
